# Generated by Django 4.2.23 on 2025-09-06 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 9, 9, 22, 57, 39, 159884, tzinfo=datetime.timezone.utc)),
        ),
    ]
