# Generated by Django 4.2.23 on 2025-08-15 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 8, 18, 17, 33, 35, 925602, tzinfo=datetime.timezone.utc)),
        ),
    ]
