# Generated by Django 4.2.23 on 2025-08-16 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 8, 19, 0, 37, 24, 989911, tzinfo=datetime.timezone.utc)),
        ),
    ]
