# Generated by Django 4.2.23 on 2025-09-08 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 9, 11, 9, 55, 54, 129458, tzinfo=datetime.timezone.utc)),
        ),
    ]
