# Generated by Django 4.2.23 on 2025-09-11 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_shipping_method_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 9, 6, 24, 384160, tzinfo=datetime.timezone.utc)),
        ),
    ]
