# Generated by Django 4.2.23 on 2025-09-11 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_grand_total_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 9, 14, 11, 43, 25, 260761, tzinfo=datetime.timezone.utc)),
        ),
    ]
