# Generated by Django 4.2.23 on 2025-09-12 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 9, 15, 9, 57, 22, 349216, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='draft', max_length=100),
        ),
    ]
