# Generated by Django 4.2.23 on 2025-09-19 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_customer_email_order_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paiementpro_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 9, 22, 9, 3, 35, 486544, tzinfo=datetime.timezone.utc)),
        ),
    ]
