# Generated by Django 4.2.23 on 2025-09-19 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_channel_order_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 9, 22, 11, 43, 14, 12262, tzinfo=datetime.timezone.utc)),
        ),
    ]
