# Generated by Django 4.2.23 on 2025-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_variantattribute_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='VariantAttribute',
        ),
        migrations.DeleteModel(
            name='VariantAttributeValue',
        ),
    ]
