# Generated by Django 4.2.23 on 2025-08-11 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 8, 14, 19, 33, 38, 568715, tzinfo=datetime.timezone.utc)),
        ),
    ]
