# Generated by Django 4.2.23 on 2025-08-11 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 8, 14, 22, 42, 8, 539469, tzinfo=datetime.timezone.utc)),
        ),
    ]
