# Generated by Django 4.2.23 on 2025-08-11 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 8, 14, 23, 45, 0, 380744, tzinfo=datetime.timezone.utc)),
        ),
    ]
