# Generated by Django 4.2.23 on 2025-08-12 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 8, 15, 9, 50, 51, 692267, tzinfo=datetime.timezone.utc)),
        ),
    ]
