# Generated by Django 4.2.23 on 2025-08-13 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 8, 16, 9, 33, 35, 177276, tzinfo=datetime.timezone.utc)),
        ),
    ]
