# Generated by Django 4.2.23 on 2025-08-04 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 8, 7, 22, 16, 57, 853565, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='en attente', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='Produit inconnu', max_length=255),
        ),
    ]
