# Generated by Django 4.2.23 on 2025-08-05 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_order_expected_delivery_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(default=datetime.datetime(2025, 8, 8, 20, 18, 52, 260337, tzinfo=datetime.timezone.utc)),
        ),
    ]
